### ISSUE TITLE
Help attempting to write a pattern that matches "any number of options"

### ISSUE THREAD

**Issue by jez** [ianthehenry/zsh-autoquoter#3]
I hate to bother you with this, but I'm running out of options 😅

I have a command like this:

```
lg [options] <query>

Options:
  -r, --regex       ...
  -s, --sensitive   ...
  ...
```

I want to be able to use zsh-autoquoter to automatically quote the `<query>`, but still pass through the options as individual arguments.

I'm struggling to come up with a zsh pattern that captures this.

My "best" try so far is:

```zsh
setopt EXTENDED_GLOB
input='lg -r -i example'
prefix='lg( -[^ ]##)#'
echo "${input#$~prefix }"
```

My interpretation of this `prefix` is that it will match "lg" followed by zero or more instances of the group "'-' then one or more non-space chars"

But for some reason, this prints

```
-r -i example
```

instead of just `example`.

The weird thing is that if i drop the enclosing pattern, it works for removing one flag:

```zsh
setopt EXTENDED_GLOB
input='lg -r -i example'
prefix='lg -[^ ]##'
echo "${input#$~prefix }"
```

```
-i example
```

If you have any clue why this might be happening, I'd be very grateful to hear what you have to say 🙇‍♂️

- - - - -

No response expected, feel free to close if you'd prefer to not have this open as an issue.

**Comment by jez** [comment]
Okay no sooner than I post this it seems I've figured it out:

https://github.com/ianthehenry/zsh-autoquoter/blob/819a615fbfd2ad25c5d311080e3a325696b45de7/zsh-autoquoter.zsh#L13

^ This line (and the corresponding zsh snippet for testing) use the non-greedy version:

> `${name#pattern}`
> `${name##pattern}`
>
> If the `pattern` matches the beginning of the value of `name`, then substitute the value of `name` with the matched portion deleted; otherwise, just substitute the value of `name`. In the first form, the smallest matching pattern is preferred; in the second form, the largest matching pattern is preferred.
>
> — https://zsh.sourceforge.io/Doc/Release/Expansion.html#Parameter-Expansion

So it seems like all the other examples in e.g. the README work because there is a trailing character like the `m` in the `git commit` prefix, or the `[^ -][^ ]#` in the `ssh` prefix, which forces the pattern to have non-zero length, meaning that zsh can't decide to not match an empty string.

For the time being, I've patched my local copy of zsh-autoquoter to use the greedy `${name##pattern}` version instead of the non-greedy one, but asking you to make that change for the whole project would be a backwards incompatible change, so I'm not sure I'd ask that of you.

In the mean time, I'll try to see if I can make a pattern that does what I want it to, now that I know it's doing non-greedy matching 😅

**Comment by ianthehenry** [comment]
Oh wow hey! Yeah, as far as I can figure this was just not a thing that zsh-autoquoter could support.

This seems like it would be generally useful though, so I just pushed a change that allows specifying `ZAQ_PREFIXES_GREEDY`, which will be matched greedily (regular `ZAQ_PREFIXES` will continue to match the shortest prefix). Could you try that and let me know if it works for you?

**Comment by jez** [comment]
Works splendidly, thanks for the quick turnaround!
